name: Cypress Tests CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container: cypress/included:15.5.0
    steps:
      # 1️⃣ Pega o código do repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Instala dependências
      - name: Install dependencies
        run: npm ci

      # 3️⃣ Executa os testes Cypress
      - name: Run Cypress headless
        run: npx cypress run --browser chrome --headless

      # 4️⃣ Publica screenshots e vídeos
      - name: Upload Cypress artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cypress-artifacts
          path: |
            cypress/screenshots
            cypress/videos
